# Generated by Django 3.2.7 on 2021-10-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
