# Generated by Django 3.2.7 on 2021-09-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        ('stocks', '0003_alter_stock_name'),
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.pool')),
                ('stocks', models.ManyToManyField(to='stocks.Stock')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
