# Generated by Django 3.2.7 on 2021-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='returns',
            field=models.FloatField(default=-0.7599555207867024),
        ),
    ]
