# Generated by Django 3.2.7 on 2021-09-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='returns',
            field=models.FloatField(default=-2.0510330684949976),
        ),
    ]
