# Generated by Django 3.2.7 on 2021-09-29 11:55

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='returns',
            field=models.FloatField(default=entries.models.generate_random_returns),
        ),
    ]
