# Generated by Django 3.1.5 on 2021-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
