# Generated by Django 3.1.5 on 2021-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_alter_pool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
